a = int(input("Enter your first number : "))
b = int(input("Enter your second number : "))
print("The sum of", a, "and", b, "is", a + b)
print("The difference of", a, "and", b, "is", a - b)
print("The product of ",a, "and", b, "is", a * b)
print("The exact decimal quotient of", a, "and", b, "is", a / b)
print("The integer quotient of", a, "and", b, "is", a // b)
print("The remainder of", a, "and", b, "is", a % b)
print(a, "raised to the power", b, "is", a**b)